language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
install:
  - pip install pytest-cov python-coveralls
    # python-coveralls requires coverage 3.
    # See https://github.com/z4r/python-coveralls/pull/41
    # (The fact that I have to specify this version number at all seems that
    # the python-coveralls packaging is broken...)
  - pip install coverage==3.7.1
script:
  - python setup.py test -a "--cov-config .coveragerc --cov=nfsn"
after_success:
  - coveralls
cache: pip
